Repository garySiladi/chat-project, pull requests merged in 2019-06, with the labels that each got.

#32 MDP-206: Homepage dynamic rendering of articles
  src/RoutesConfig.ts
  src/components/Header/Navigation.tsx
  src/components/Header/UserIcon.tsx
  src/components/Header/index.tsx
  src/components/Home.tsx
  src/components/Home/index.tsx
  src/components/Homepage/ArticleWrapper.tsx
  src/components/Homepage/Button.tsx
  src/components/Homepage/DescriptionWrapper.tsx
  src/components/Homepage/LandingPageWrapper.tsx
  src/components/Homepage/NewestArticles.tsx
  src/components/Homepage/NewestArticlesWrapper.tsx
  src/components/Layout/index.tsx
  src/style/custom.css
  tailwind.js
Labels: senior review needed

#42 fixed tsc errors
  src/components/Homepage/ArticleWrapper.tsx
  src/stories/index.tsx
Labels: senior review needed

#39 MDP-211: Refactor footer
  src/components/Footer/Contacts.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/Info.tsx
  src/components/Footer/Location.tsx
  src/components/Footer/Logo.tsx
  src/static/svg/logoFooter.png
Labels: peer review needed

#40 MDP-213: Thumbnail Update
  src/components/Homepage/ArticleWrapper.tsx
  src/components/Thumbnail/Button.tsx
  src/components/Thumbnail/Date.tsx
  src/components/Thumbnail/Description.tsx
  src/components/Thumbnail/Image.tsx
  src/components/Thumbnail/Name.tsx
  src/components/Thumbnail/Thumbnail.tsx
  src/components/Thumbnail/ThumbnailArticle.tsx
  src/components/Thumbnail/ThumbnailTherapy.tsx
  src/static/svg/homer.svg
  src/stories/index.tsx
  tailwind.js
Labels: peer approved, senior review needed

#45 Sr/article rendering update
  src/RoutesConfig.ts
  src/components/Homepage/ArticleWrapper.tsx
  src/components/Homepage/NewestArticles.tsx
Labels: peer approved, senior review needed

#43 MDP-215: Create ChatInfo text with rotated style
  src/components/ChatInfo/TextBackground.tsx
  src/components/ChatInfo/index.tsx
  src/stories/index.tsx
Labels: peer approved, senior review needed

#28 MDP-196: Create "schedule" component
  src/components/Schedule/AvailabilityBar.tsx
  src/components/Schedule/Counter.tsx
  src/components/Schedule/DayInfoMessage.tsx
  src/components/Schedule/ProgressBar.tsx
  src/components/Schedule/Reservation.tsx
  src/components/Schedule/ReservationInfo.tsx
  src/components/Schedule/index.tsx
  src/static/svg/minusIcon.svg
  src/static/svg/plusIcon.svg
  src/stories/index.tsx
  tailwind.js
Labels: senior review needed

#36 MDP-210:Create "article" component
  index.html
  src/components/ArticlesCollection/ArticlesCollection.tsx
  src/components/ArticlesCollection/Container.tsx
  src/components/Description/Description.tsx
  src/components/Description/DescriptionAndButton.tsx
  src/components/Description/DescriptionWrapper.tsx
  src/components/Homepage/LandingPageWrapper.tsx
  src/index.html
  src/stories/index.tsx
  tailwind.js
Labels: changes requested

#47 MDP-148: fix master, add cypress
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/integration/homepage-visit.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  jest.config.js
  package.json
  src/components/Header/index.tsx
  src/index.html
  src/stories/index.tsx
Labels: senior review needed
