Repository garySiladi/chat-project, pull requests merged in 2019-05, with the labels that each got.

#14 add viewport support into storybook
  .storybook/addons.js
  .storybook/config.js
  .storybook/viewports.js
  package-lock.json
  package.json
Labels: approved

#15 add husky and no-default-export
  package-lock.json
  package.json
  src/Router.tsx
  src/components/ButtonExample.tsx
  src/components/Counter.tsx
  src/components/Example.tsx
  src/components/Home.tsx
  src/components/Testing.tsx
  src/index.tsx
  src/store/index.ts
  src/stories/index.tsx
  tslint.json
Labels: needs review

#11 MDP-184: Universal Popup Component
  package-lock.json
  src/components/Popup/Button.tsx
  src/components/Popup/CloseButton.tsx
  src/components/Popup/InfoMessage.tsx
  src/components/Popup/Message.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/Storybook/CancelReservationPopup.tsx
  src/components/Popup/Storybook/CreditPopup.tsx
  src/components/Popup/Storybook/ErrorPopup.tsx
  src/components/Popup/Storybook/RegistrationPopup.tsx
  src/components/Popup/TextUnderButton.tsx
  src/components/Testing.tsx
  src/stories/index.tsx
Labels: needs review

#10 MDP-188: Header component
  src/components/Header/Header.tsx
  src/components/Header/ImageHeader.tsx
  src/components/Header/Menu.tsx
  src/components/Header/Navigation.tsx
  src/components/Header/UserIcon.tsx
  src/components/Header/UserInfo.tsx
  src/components/Header/UserMenu.tsx
  src/components/Header/UserProfile.tsx
  src/static/svg/chatLogo.png
  src/static/svg/cogs.svg
  src/static/svg/euroSign.svg
  src/static/svg/idBadge.svg
  src/static/svg/menu.svg
  src/static/svg/powerOff.svg
  src/static/svg/userIcon.svg
  src/stories/index.tsx
  src/style/custom.css
  tailwind.js
Labels: needs review

#12 MDP-166: Footer component
  package-lock.json
  src/components/Icon.tsx
  src/components/footer/Contacts.tsx
  src/components/footer/Info.tsx
  src/components/footer/Location.tsx
  src/components/footer/Logo.tsx
  src/components/footer/index.tsx
  src/static/svg/email.svg
  src/static/svg/facebook-square.svg
  src/static/svg/icon-checkbox-checked.svg
  src/static/svg/icon-checkbox-empty.svg
  src/static/svg/icon-cogs.svg
  src/static/svg/icon-email.svg
  src/static/svg/icon-euro-sign.svg
  src/static/svg/icon-id-badge.svg
  src/static/svg/icon-phone.svg
  src/static/svg/icon-place.svg
  src/static/svg/icon-radio-empty.svg
  src/static/svg/icon-radio-full.svg
  src/static/svg/instagram.svg
  src/static/svg/oval-mobile.svg
  src/static/svg/ovals.svg
  src/static/svg/yellowfooterbig.svg
  src/stories/index.tsx
  src/style/custom.css
Labels: changes requested

#19 add tailwind change
  tailwind.js
Labels: needs review

#21 MDP-200: Adjust footer design
  src/components/footer/Contacts.tsx
  src/components/footer/Location.tsx
  src/components/footer/Logo.tsx
  src/components/footer/index.tsx
  src/style/custom.css
Labels: needs review

#16 MDP-195: buttons and input component
  package-lock.json
  src/components/Button.tsx
  src/components/Input.tsx
  src/stories/index.tsx
  tailwind.js
Labels: needs review

#26 MDP-195: Buttons stretching
  src/components/Button.tsx
  src/stories/index.tsx
  tslint.json
Labels: approved

#25 MDP-203: rename footer component
  src/components/Footer/Contacts.tsx
  src/components/Footer/Info.tsx
  src/components/Footer/Location.tsx
  src/components/Footer/Logo.tsx
  src/components/Footer/index.tsx
  src/stories/index.tsx
Labels: approved

#29 Refactor button
  src/components/Button.tsx
  src/components/ButtonExample.tsx
  src/stories/index.tsx
Labels: approved

#13 MDP-192: Thumbnail component
  src/components/Thumbnail/Button.tsx
  src/components/Thumbnail/Description.tsx
  src/components/Thumbnail/Image.tsx
  src/components/Thumbnail/Name.tsx
  src/components/Thumbnail/Thumbnail.tsx
  src/static/svg/homer.svg
  src/stories/index.tsx
  tailwind.js
Labels: approved, needs review

#20 MDP-189: Hamburger menu
  src/components/Header/HamburgerMenu.tsx
  src/components/Header/Header.tsx
  src/components/Header/ImageHeader.tsx
  src/components/Header/Menu.tsx
  src/static/svg/closeImg.svg
  tailwind.js
Labels: approved, needs review

#6 MDP-185: Landing page component
  src/components/Home.tsx
  src/components/Homepage/BackgroundImage.tsx
  src/components/Homepage/Button.tsx
  src/components/Homepage/Description.tsx
  src/components/Homepage/DescriptionWrapper.tsx
  src/components/Homepage/Icon.tsx
  src/components/Homepage/LandingPageWrapper.tsx
  src/components/Homepage/List.tsx
  src/components/Homepage/Logo.tsx
  src/static/svg/backgroundImage.svg
  src/static/svg/blueOval.svg
  src/static/svg/greenOval.svg
  src/static/svg/icon-therapy-type-deti-4-15.svg
  src/static/svg/icon-therapy-type-deti-do-3-rokov.svg
  src/static/svg/icon-therapy-type-pre-dospeleho.svg
  src/static/svg/icon-therapy-type-pre-dospelych.svg
  src/static/svg/logo-color-big.png
  src/static/svg/orangeOval.svg
  src/static/svg/pinkOval.svg
  src/stories/index.tsx
  src/style/custom.css
Labels: approved, needs review

#17 MDP-198:Article page component
  src/components/ArticlePage/Article.tsx
  src/components/ArticlePage/ArticleContainer.tsx
  src/static/svg/articleImage.png
  src/stories/index.tsx
Labels: needs review

#33 MDP-197: Schedule Filter
  src/Router.tsx
  src/components/ScheduleFilter/CheckboxLine.tsx
  src/components/ScheduleFilter/Dropdown.tsx
  src/components/ScheduleFilter/List.tsx
  src/components/ScheduleFilter/ScheduleFilter.tsx
  src/static/svg/icon-filter.svg
  src/stories/index.tsx
  tailwind.js
Labels: approved

#34 Update Icon and Button component
  src/components/Button.tsx
  src/components/Icon.tsx
  src/stories/index.tsx
Labels: needs review

#31 MDP-208: User dropdown menu
  src/components/Header/Header.tsx
  src/components/Header/UserDropdownMenu.tsx
  src/components/Header/UserProfile.tsx
Labels: changes requested

#27 MDP-204: Utility getDateByTimestamp
  package-lock.json
  package.json
  src/utils/date.test.ts
  src/utils/date.ts
  src/utils/sum.test.ts
  src/utils/sum.ts
Labels: changes requested

#35 Pg/tailwind update
  package-lock.json
  package.json
  src/Router.tsx
  src/components/ArticlePage/Article.tsx
  src/components/ArticlePage/ArticleContainer.tsx
  src/components/Button.tsx
  src/components/Footer/Contacts.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/Info.tsx
  src/components/Footer/Location.tsx
  src/components/Footer/Logo.tsx
  src/components/Header/HamburgerMenu.tsx
  src/components/Header/Header.tsx
  src/components/Header/Menu.tsx
  src/components/Header/Navigation.tsx
  src/components/Header/UserDropdownMenu.tsx
  src/components/Header/UserIcon.tsx
  src/components/Header/UserInfo.tsx
  src/components/Header/UserMenu.tsx
  src/components/Header/UserProfile.tsx
  src/components/Homepage/Button.tsx
  src/components/Homepage/Description.tsx
  src/components/Homepage/DescriptionWrapper.tsx
  src/components/Homepage/Icon.tsx
  src/components/Homepage/LandingPageWrapper.tsx
  src/components/Homepage/List.tsx
  src/components/Icon.tsx
  src/components/Input.tsx
  src/components/Popup/Button.tsx
  src/components/Popup/CloseButton.tsx
  src/components/Popup/InfoMessage.tsx
  src/components/Popup/Message.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/TextUnderButton.tsx
  src/components/ScheduleFilter/CheckboxLine.tsx
  src/components/ScheduleFilter/Dropdown.tsx
  src/components/ScheduleFilter/List.tsx
  src/components/ScheduleFilter/ScheduleFilter.tsx
  src/components/Thumbnail/Button.tsx
  src/components/Thumbnail/Description.tsx
  src/components/Thumbnail/Name.tsx
  src/components/Thumbnail/Thumbnail.tsx
  src/stories/index.tsx
  src/style/custom.css
  src/style/index.css
  tailwind.js
  tailwind.txt
Labels: needs review
